services:
  Authentication.infrastructure.Token.JWTAuthenticationTokenService:
    class: ../../../../contexts/Authentication/AuthenticationToken/infrastructure/Services/JWT/JWTAuthenticationTokenService
